library(LaplacesDemon)
library(tidyverse)

test_alpha <- 0.5
K <- 3
n <- 1000

sim <- rdirichlet(n, alpha = rep(test_alpha, K)) %>%
  as.data.frame() %>%
  as_tibble()

sum_sim <- sim %>% 
  pivot_longer(
    cols = everything()
  ) %>%
  group_by(name) %>%
  summarize(
    mean = mean(value),
    sd = sd(value)
  )

print(sum_sim)

# This was to examing the output of rngs generated by the Dirichlet Distribution
# chosen by the authors of https://doi.org/10.1371/journal.pcbi.1011580
# I wanted to see why alpha = 2 was selected.
# It appears that adjusting alpha changes the standard deviation of the random
# numbers generated by the dist, and I can only assume that the value of 2 was
# chosen as 1 returns too high of an sd and 3 returns too low? Value > 2 would
# strengthen the prior in case we want to enforce stricter structure on the
# model. Value of < 2 would weaken the prior
